channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - numpy
  - matplotlib
  - python-wget
  - gzip
  - scipy
  - pip
  - pip:
    - git+https://github.com/OpenHydrology/lmoments3.git
    - scikit-stats
