channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - numpy=1.16.6
  - matplotlib=3.2.2*
  - python-wget
  - gzip
  - scipy=1.5.2
  - pip
  - pip:
    - git+https://github.com/OpenHydrology/lmoments3.git
    - scikit-stats==0.1.2
